### ISSUE TITLE
Home Assistant Error: Error setting up platform legacy

### ISSUE THREAD

**Issue by cjs28** [jrlucier/eero_tracker#19]
I have just set this integration up running the latest version of home assistant and I am receiving the following error on start up and I do not see any device trackers listed for my devices.

Home Assistant Version: 105.5
HACS Eero Tracker Install: 1.0.5

Error from Home Assistant:
Wed Feb 19 2020 20:26:18 GMT-0600 (Central Standard Time)
Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 64, in async_setup_legacy
    self.platform.get_scanner, hass, {DOMAIN: self.config}
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/eero_tracker/device_tracker.py", line 35, in get_scanner
    return EeroDeviceScanner(hass, config[DOMAIN])
  File "/config/custom_components/eero_tracker/device_tracker.py", line 56, in __init__
    self.__scan_interval = int(config[CONF_SCAN_INTERVAL])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.timedelta'

**Comment by giu1io** [comment]
I have the same issue. I downgraded to the previous version of Eero Tracker to fix the problem.

**Comment by jrlucier** [comment]
Thanks for the report -- I'll take a look shortly to see if I can reproduce

**Comment by jrlucier** [comment]
@giu1io  and @cjs28 Try the latest -- I think I have it fixed up :)

I pushed it to releases as well.  If it's still broken, feel free to reopen or create a new issue and reference this one.

**Comment by cjs28** [comment]
Yep the change looks good for me. Devices are showing up in my home assistant.

Thank You, for the fix!
