### ISSUE TITLE
Updated eero_tracker with new features

### ISSUE THREAD

**Issue by rsnodgrass** [jrlucier/eero_tracker#20]
Updated eero_tracker with new features.  @jrlucier please release whenever you are comfortable.

* added only_networks option to allow specifying which eero networks to include (in case multiple networks are under a single email address, like a work network or second home)
* added only_wireless option (defaulted on) to enable configuring whether non-wireless devices are tracked
* updated to README to describe new features
* code cleanup and logging improvements

**Comment by jrlucier** [comment]
I'll pull it down and test it out tonight.   :+1: :+1: 

Thanks for the improvements!

**Comment by rsnodgrass** [comment]
Would be great to also add jrlucier/eero_tracker to the list of defaults at:

https://github.com/hacs/default/blob/master/integration

Only you can do that (as owner of the repository)...I already tried!  

You can edit in place, adding the following, and then submit a Pull Request:

     "jrlucier/eero_tracker",

Thanks!

**Comment by jrlucier** [comment]
Sorry for the delay, code is tested, cut and released. Awesome job!  I'll work on getting us on the master integration list for HACS.  I'll create a new issue just for that.
