### ISSUE TITLE
Some devices, with nicknames, only show up as device_tracker.<macaddress>

### ISSUE THREAD

**Issue by rsnodgrass** [jrlucier/eero_tracker#21]
I've noticed some devices show up as device_tracker.<macaddress> only, even though they have nicknames. May be due to apostrophe (') in the nickname, since in the eero logs the nickname appears, but as a device tracker only the mac is used.  This has been an issue for a long time.

**Comment by rsnodgrass** [comment]
I think this has something to do with the known_devices.yaml legacy file not being updated when there is a nickname change.

CONFIRMED: I deleted known_devices.yaml, and the name updated to the latest that was configured on my eero.

**Comment by jrlucier** [comment]
Hmm, might require some investigating.  I wonder if it's a "device_tracker" friendly name limitation?  The one limit I know of is once a device tracker is initialized in HA (by UID/MAC), we can no longer update the friendly name.  It's persisted with the original default or whatever the user might change it to afterwards.

**Comment by jrlucier** [comment]
Correct -- we can't update it once it has been created in known_devices

**Comment by rsnodgrass** [comment]
Do you know what we would have to change to stop using "legacy" tracker and move to whatever is the latest style that doesn't use known_devices.yaml?

**Comment by jrlucier** [comment]
It'd take a weekend or two, and a pretty big rewrite most likely.  I've been waiting for the core upstream components to migrate off of it so I can mimic what they did -- but none of the similar integrations have changed over.  Probably worth a revisit in a couple of months.

**Comment by rsnodgrass** [comment]
Sounds good.
