### ISSUE TITLE
Deprecated folder structure

### ISSUE THREAD

**Issue by jrlucier** [jrlucier/eero_tracker#3]
From the logs: 
> Integrations need to be in their own folder. Change device_tracker/eero_tracker.py to eero_tracker/device_tracker.py. This will stop working soon.

**Comment by rsnodgrass** [comment]
I just submitted a pull request to fix this as well as other structural changes that Home Assistant recently released.

**Comment by jrlucier** [comment]
Thanks @rsnodgrass ! -- reviewing it right now :)

**Comment by jrlucier** [comment]
Made some small tweaks to get in the custom_components directory (for those overlaying the zip). Updated the custom_updater to match as well.

**Comment by rsnodgrass** [comment]
Excellent. Thanks!!
  

  
  

  
  
>
